DROP TABLE IF EXISTS itemInstance;
DROP TABLE IF EXISTS pCharSkill;
DROP TABLE IF EXISTS playerCharacter;
DROP TABLE IF EXISTS itemClass;
DROP TABLE IF EXISTS characterClass;
DROP TABLE IF EXISTS player;
DROP TABLE IF EXISTS skill;